### ISSUE TITLE
Test failures: ExactSolver doesn't expect 'label' argument

### ISSUE THREAD

**Issue by hhtong** [dwave-examples/knapsack#24]
A couple of the examples use the ExactSolver in tests (it's passed in as the sampler). The ExactSolver does not take in any keyword arguments, so passing in 'label' causes the test to fail with `TypeError: sample() got an unexpected keyword argument 'label'`.

I'm wondering if we should update the ExactSolver to just swallow keyword arguments. Or if this is considered bad practice, in which case we just need to modify a few examples including this one.

**Comment by hhtong** [comment]
@randomir  @JoelPasvolsky

**Comment by randomir** [comment]
Practice has taught me to err on the side of extensibility. That's why all runnables in dwave-hybrid accept **kwargs (ignoring the unhandled ones). The same for all other samplers in Ocean (that I can think of): greedy, tabu, neal, qpu/leaphybrid...

I would do the same in the `ExactSolver`, if for nothing else then for consistency. @arcondello might have a strong reason for current implementation, though.

**Comment by JoelPasvolsky** [comment]
Let me know if you need me to wrap it here so these tests can pass already now, otherwise I'll wait to see if we update `ExactSolver` to accept unhandled **kwargs.

**Comment by arcondello** [comment]
I have found the opposite of @randomir , where swallowing unknown kwargs leads to bugs like misspelled kwargs, which is why I do not support them in `ExactSolver`. It feels like the wrong solution to this problem to me. Shouldn't this be the place that [`MockSampler` from dwave-systems](https://github.com/dwavesystems/dwave-system/blob/master/dwave/system/testing.py) is used? And if we need a deterministic version, that seems like a feature request for `MockSampler`.

**Comment by arcondello** [comment]
Ah, I see the consistency argument. I didn't know we had added `**kwargs` to neal etc, I would have objected if I had noticed. But since that cat is out of the bag, I suppose we should be consistent.

**Comment by hhtong** [comment]
Perhaps we could pass warnings along when a kwarg is being swallowed.

**Comment by mcfarljm** [comment]
> 
> 
> It feels like the wrong solution to this problem to me. Shouldn't this be the place that [a mock sampler from dwave-systems](https://github.com/dwavesystems/dwave-system/blob/master/dwave/system/testing.py) is used? And if we need a deterministic version, and/or DQM version, that should be a feature request for dwave-system.

In this case it's using `ExactSolver` to verify that the problem formulation produces the expected ground state energy.

A couple of easy short-term solutions that could be implemented here pending other API updates to the solvers:
1. Check the sampler instance prior to calling `sampler.sample` and pass `label` conditionally.  Or
2. Add `**sampler_kwargs` to `solve_knapsack` and then only pass in the `label` option in the main code, not in the tests that use the `ExactSolver`.

**Comment by hhtong** [comment]
The change to consistently swallow unknown kwargs has already been merged and released in the latest dimod version (see PR here: https://github.com/dwavesystems/dimod/pull/796). Just waiting on a release of the sdk now. Since this fix is already on the way, I think it's fine to leave this alone for now.

**Comment by hhtong** [comment]
Fixed with `dwave-ocean-sdk==3.4.0`.
